### ISSUE TITLE
Last commit breaks Android build

### ISSUE THREAD

**Issue by tellibus** [Rohfosho/CordovaCallNumberPlugin#15]
Project build fails on Android with latest commit (978d9361ca53e0bbc0f47443a5aab0655b6b7d7b).

Here are some of the failing dev. environment details:

```{r, engine='sh', count_lines}
$ cordova -version
4.1.2
```

```{r, engine='sh', count_lines}
$ java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```

```{r, engine='sh', count_lines}
$ ant -version
Apache Ant(TM) version 1.9.6 compiled on June 29 2015
```

```{r, engine='sh', count_lines}
$ cordova build android
[...]
-compile:
    [javac] Compiling 28 source files to <cordova_project_path>/platforms/android/ant-build/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] <cordova_project_path>/platforms/android/src/mx/ferreyra/callnumber/CFCallNumber.java:49: error: cannot find symbol
    [javac]       PackageManager packageManager = cordova.getPackageManager();
    [javac]       ^
    [javac]   symbol:   class PackageManager
    [javac]   location: class CFCallNumber
    [javac] <cordova_project_path>/platforms/android/src/mx/ferreyra/callnumber/CFCallNumber.java:49: error: cannot find symbol
    [javac]       PackageManager packageManager = cordova.getPackageManager();
    [javac]                                              ^
    [javac]   symbol:   method getPackageManager()
    [javac]   location: variable cordova of type CordovaInterface
    [javac] <cordova_project_path>/platforms/android/src/mx/ferreyra/callnumber/CFCallNumber.java:50: error: cannot find symbol
    [javac]       List activities = packageManager.queryIntentActivities(intent, PackageManager.MATCH_DEFAULT_ONLY);
    [javac]       ^
    [javac]   symbol:   class List
    [javac]   location: class CFCallNumber
    [javac] <cordova_project_path>/platforms/android/src/mx/ferreyra/callnumber/CFCallNumber.java:50: error: cannot find symbol
    [javac]       List activities = packageManager.queryIntentActivities(intent, PackageManager.MATCH_DEFAULT_ONLY);
    [javac]                                                              ^
    [javac]   symbol:   variable intent
    [javac]   location: class CFCallNumber
    [javac] <cordova_project_path>/platforms/android/src/mx/ferreyra/callnumber/CFCallNumber.java:50: error: cannot find symbol
    [javac]       List activities = packageManager.queryIntentActivities(intent, PackageManager.MATCH_DEFAULT_ONLY);
    [javac]                                                                      ^
    [javac]   symbol:   variable PackageManager
    [javac]   location: class CFCallNumber
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: <cordova_project_path>/platforms/android/src/org/apache/cordova/file/ContentFilesystem.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 5 errors
    [javac] 3 warnings

BUILD FAILED
<ant_path>/ant/build.xml:716: The following error occurred while executing this line:
<ant_path>/ant/build.xml:730: Compile failed; see the compiler error output for details.

Total time: 5 seconds

<cordova_project_path>/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,<cordova_project_path>/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error: <cordova_project_path>/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

For the record, project is building ok on iOS with both previous (79333b32edba0d9f04529821222b955ad2d404a2) and latest commits (978d9361ca53e0bbc0f47443a5aab0655b6b7d7b).

Project is building ok on Android with previous commit (79333b32edba0d9f04529821222b955ad2d404a2).

**Comment by nishilshah17** [comment]
Thanks for the report. Committed some changes.

**Comment by tellibus** [comment]
Indeed. Many thanks!
